project:
  type: book
  output-dir: docs
  

book:
  title: "PsyDataViz"
  author: "Jane Doe"
  date: "2/13/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - heatmaps.qmd
    - scatterplots.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

