project:
  type: book
  output-dir: docs
  

book:
  title: "PsyDataViz"
  author: "James Curley"
  date: "2/13/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - scatterplots.qmd
    - lines.qmd
    - histograms.qmd
    - distributionsgroups.qmd
    - bar.qmd
    - smallmult.qmd
    - heatmaps.qmd
    - areacharts.qmd
    - bumps.qmd
    - savingexporting.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

